version: "3.8"
name: aims

services:
  account-db:
    image: mysql:latest
    container_name: account_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=accounts
      - MYSQL_USER=aims
      - MYSQL_PASSWORD=aims
    ports:
      - "3307:3306"
    volumes:
      - account_db_data:/var/lib/mysql

  account-ms:
    build: .
    image: aims_account_ms
    container_name: account_ms
    depends_on:
      - account-db
      - account-ldap
    links:
      - account-db
      - account-ldap
    environment:
      - PORT=3000
      - MYSQL_DATABASE=accounts
      - MYSQL_USER=aims
      - MYSQL_PASSWORD=aims
      - MYSQL_HOST=account-db
      - MYSQL_PORT=3306
      - JWT_SECRET=6jweWqIJNJ9aozbxQ6K4
      - LDAP_URL=ldap://account-ldap:389
      - LDAP_ROOT=cn=admin,dc=AIMS,dc=edu,dc=co
      - LDAP_PASSWORD=aims
    ports:
      - "3001:3000"

volumes:
  account_db_data:
