version: "3.8"
name: aims

services:
  account-db:
    image: mysql:latest
    container_name: account_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=accounts
      - MYSQL_USER=aims
      - MYSQL_PASSWORD=aims
    ports:
      - "3307:3306"
    volumes:
      - account_db_data:/var/lib/mysql

  account-ms:
    build: .
    image: aims_account_ms
    container_name: account_ms
    depends_on:
      - account-db
      - account-ldap
    links:
      - account-db
      - account-ldap
    environment:
      - PORT=3000
      - MYSQL_DATABASE=accounts
      - MYSQL_USER=aims
      - MYSQL_PASSWORD=aims
      - MYSQL_HOST=account-db
      - MYSQL_PORT=3306
      - JWT_SECRET=6jweWqIJNJ9aozbxQ6K4
      - LDAP_URL=ldap://account-ldap:389
      - LDAP_ROOT=cn=admin,dc=AIMS,dc=edu,dc=co
      - LDAP_PASSWORD=aims
    ports:
      - "3001:3000"

  account-ldap:
    image: osixia/openldap:1.2.2
    container_name: account-ldap
    restart: always
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "aims"
      LDAP_DOMAIN: "aims.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "aims"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - account_ldap_data:/var/lib/ldap
      - account_ldap_config:/etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "aims.edu.co"

volumes:
  account_db_data:
  account_ldap_data:
  account_ldap_config:
